### ISSUE TITLE
radar-lidar calibration

### ISSUE THREAD

**Issue by AlgoJay1991** [autocore-ai/calibration_tools#1]
我在网上看到贵公司的毫米波雷达标定专利，请问贵公司是否计划将毫米波雷达标定的代码开源？谢谢

**Comment by JianKangEgon** [comment]
@dangerous-xu 感谢您的来信，目前暂无公开专利相关内容的计划。

**Comment by pedestrain123** [comment]
> 我在网上看到贵公司的毫米波雷达标定专利，请问贵公司是否计划将毫米波雷达标定的代码开源？谢谢

请问这家公司名字叫什么？专利可以分享一下链接吗？谢谢
