### ISSUE TITLE
Paper

### ISSUE THREAD

**Issue by CustSlaming** [autocore-ai/calibration_tools#3]
Do you have any papers related to this project?

**Comment by JianKangEgon** [comment]
@CustSlaming  which one of these tools do you refer to ?

**Comment by zhongchong7** [comment]
@JianKangEgon Could you have paper about /lidar-cam-calib-related? If yes, could you please share it with me? Thanks!

**Comment by JianKangEgon** [comment]
> @JianKangEgon Could you have paper about /lidar-cam-calib-related? If yes, could you please share it with me? Thanks!

@zhongchong7 sorry, there is no such paper published regarding lidar-cam-calib.
