### ISSUE TITLE
New checker board error

### ISSUE THREAD

**Issue by Haishanliu** [autocore-ai/calibration_tools#4]
Hi, we tried to use this package to calibrate our lidar and camera. Our checkboard pattern is 7*9, each square size is 10cm * 10cm. I modified the function in feature_extract.cpp line 840, cv::Size2i patternNum(7,9) according to our checkboard. Only with this modification, we got the following error：

cv2.error: OpenCV(4.1.0) C:\projects\opencv-python\opencv\modules\calib3d\src\solvepnp.cpp:92: error: (-215:Assertion failed) ( (npoints >= 4) || (npoints == 3 && flags == SOLVEPNP_ITERATIVE && useExtrinsicGuess) ) && npoints == std::max(ipoints.checkVector(2, CV_32F), ipoints.checkVector(2, CV_64F)) in function 'cv::solvePnP'

I already changed the feature lauuch file and camera.yaml file.

Any suggestions for this bug will be appreciated.

**Comment by JianKangEgon** [comment]
@alanmengg do you have any idea regarding this issue?

**Comment by alanmengg** [comment]
> 

it seems opencv doesn't find the pattern of your checkboard, could u share your calibration img?

**Comment by alanmengg** [comment]
> Hi, we tried to use this package to calibrate our lidar and camera. Our checkboard pattern is 7*9, each square size is 10cm * 10cm. I modified the function in feature_extract.cpp line 840, cv::Size2i patternNum(7,9) according to our checkboard. Only with this modification, we got the following error：
> 
> cv2.error: OpenCV(4.1.0) C:\projects\opencv-python\opencv\modules\calib3d\src\solvepnp.cpp:92: error: (-215:Assertion failed) ( (npoints >= 4) || (npoints == 3 && flags == SOLVEPNP_ITERATIVE && useExtrinsicGuess) ) && npoints == std::max(ipoints.checkVector(2, CV_32F), ipoints.checkVector(2, CV_64F)) in function 'cv::solvePnP'
> 
> I already changed the feature lauuch file and camera.yaml file.
> 
> Any suggestions for this bug will be appreciated.
it seems opencv doesn't find the pattern of your checkboard, could u share your calibration img?

**Comment by alanmengg** [comment]
> Hi, we tried to use this package to calibrate our lidar and camera. Our checkboard pattern is 7*9, each square size is 10cm * 10cm. I modified the function in feature_extract.cpp line 840, cv::Size2i patternNum(7,9) according to our checkboard. Only with this modification, we got the following error：
> 
> cv2.error: OpenCV(4.1.0) C:\projects\opencv-python\opencv\modules\calib3d\src\solvepnp.cpp:92: error: (-215:Assertion failed) ( (npoints >= 4) || (npoints == 3 && flags == SOLVEPNP_ITERATIVE && useExtrinsicGuess) ) && npoints == std::max(ipoints.checkVector(2, CV_32F), ipoints.checkVector(2, CV_64F)) in function 'cv::solvePnP'
> 
> I already changed the feature lauuch file and camera.yaml file.
> 
> Any suggestions for this bug will be appreciated.

it seems opencv doesn't find the pattern of your checkboard, could u share your calibration img?

**Comment by zhangyuran-gg** [comment]
> > Hi, we tried to use this package to calibrate our lidar and camera. Our checkboard pattern is 7*9, each square size is 10cm * 10cm. I modified the function in feature_extract.cpp line 840, cv::Size2i patternNum(7,9) according to our checkboard. Only with this modification, we got the following error：
> > cv2.error: OpenCV(4.1.0) C:\projects\opencv-python\opencv\modules\calib3d\src\solvepnp.cpp:92: error: (-215:Assertion failed) ( (npoints >= 4) || (npoints == 3 && flags == SOLVEPNP_ITERATIVE && useExtrinsicGuess) ) && npoints == std::max(ipoints.checkVector(2, CV_32F), ipoints.checkVector(2, CV_64F)) in function 'cv::solvePnP'
> > I already changed the feature lauuch file and camera.yaml file.
> > Any suggestions for this bug will be appreciated.
> 
> it seems opencv doesn't find the pattern of your checkboard, could u share your calibration img?

Hello, I also encountered this error，the calibration image is as follows
![image](https://github.com/user-attachments/assets/3d05719c-319d-49b9-9e17-42e913b6bb94)
![jz_01](https://github.com/user-attachments/assets/a243e4bb-0807-43d3-8840-d1ce665b8ebc)

**Comment by zhangyuran-gg** [comment]
> Hi, we tried to use this package to calibrate our lidar and camera. Our checkboard pattern is 7*9, each square size is 10cm * 10cm. I modified the function in feature_extract.cpp line 840, cv::Size2i patternNum(7,9) according to our checkboard. Only with this modification, we got the following error：
> 
> cv2.error: OpenCV(4.1.0) C:\projects\opencv-python\opencv\modules\calib3d\src\solvepnp.cpp:92: error: (-215:Assertion failed) ( (npoints >= 4) || (npoints == 3 && flags == SOLVEPNP_ITERATIVE && useExtrinsicGuess) ) && npoints == std::max(ipoints.checkVector(2, CV_32F), ipoints.checkVector(2, CV_64F)) in function 'cv::solvePnP'
> 
> I already changed the feature lauuch file and camera.yaml file.
> 
> Any suggestions for this bug will be appreciated.

你好，请问你解决这个问题了吗
