### ISSUE TITLE
li_calib not working for OS-128

### ISSUE THREAD

**Issue by zillur01** [autocore-ai/calibration_tools#5]
I configured the launch file accordingly with proper topic names and lidar model. The gui is not opening at all. Also, shows warning that OS-128 is not supported.
![Screenshot from 2023-07-27 13-48-58](https://github.com/autocore-ai/calibration_tools/assets/54721606/d5249e6b-db85-418b-b8ed-b7b19ec8ce5d)

**Comment by JianKangEgon** [comment]
In this case, you may need overwrite the struct "OusterPointXYZIRT" in "pcl_utils.h" to exclude the field "ring" in accordance with your Lidar parse mode.
