### ISSUE TITLE
build error: no matching function for call to pcl::fromROSMsg(*msg, *cloud_main_lidar_current_)

### ISSUE THREAD

**Issue by AndriiChumak145** [autocore-ai/calibration_tools#6]
Hi, I'm trying to build multi_lidar_calib on Ubuntu 22.04 with ros humble. I got stuck on the problem with pcl_conversions, as you can see in the screenshot.
![image](https://github.com/autocore-ai/calibration_tools/assets/23037837/664d30fc-3e68-496e-a152-908842647bdd)

I couldn't solve the problem by installing ros-humble-pcl-conversions and libpcl-conversions-dev. The fact that I don't get errors with `#include <pcl_conversions/pcl_conversions.h>` in the multi_lidar_calib.cpp file suggests that the library is installed correctly. 
Does anyone have an idea what I might have done wrong, or could someone explain how they managed to install the project successfully?

Thank you!

**Comment by JianKangEgon** [comment]
It seems that the PCL version of ros2 humble is not well-compatible, this calibration tool was tested in ros2-galactic and worked well. Could you try it again in ros2-galactic?
