### ISSUE TITLE
lidar-lidar calibration main lidar selection

### ISSUE THREAD

**Issue by stefanofio** [autocore-ai/calibration_tools#8]
Hi, I was trying to test the lidar-lidar calibration package with the bag given as an example and everything works fine if I use the velodyne (360 FoV) as the main one and the Robosense as the sub. Since no requirement is given on who should be the main and who should be the sub I tried inverting their roles by swapping the topics in the config file. Bu I get this error:

[multi_lidar_calib-1] multi_lidar_calib: /build/pcl-gWGA5r/pcl-1.10.0+dfsg/kdtree/include/pcl/kdtree/impl/kdtree_flann.hpp:138: int pcl::KdTreeFLANN<PointT, Dist>::nearestKSearch(const PointT&, int, std::vector<int>&, std::vector<float>&) const [with PointT = pcl::PointXYZI; Dist = flann::L2_Simple<float>]: Assertion `point_representation_->isValid (point) && "Invalid (NaN, Inf) point coordinates given to nearestKSearch!"' failed.
[ERROR] [multi_lidar_calib-1]: process has died [pid 16293, exit code -6, cmd '/home/sagittarius/idv_code/idv-dev/install/multi_lidar_calib/lib/multi_lidar_calib/multi_lidar_calib --ros-args -r __node:=multi_lidar_calib_node --params-file /home/sagittarius/idv_code/idv-dev/install/multi_lidar_calib/share/multi_lidar_calib/config/params.yaml'].

What can I do about it?
Is there any requirement in the pointclouds' FoV that should be taken into account to make the calibration work?

Thanks in advance

**Comment by JianKangEgon** [comment]
Hi @stefanofio 
Actually, there has nothing to do with the FoV of a single Lidar, as long as both lidars have overlapped areas.  The more overlapped areas, the better the results.
The error here seems that there is something wrong with your lidar points, could check your lidar driver and parsing file first?

**Comment by stefanofio** [comment]
> Hi @stefanofio Actually, there has nothing to do with the FoV of a single Lidar, as long as both lidars have overlapped areas. The more overlapped areas, the better the results. The error here seems that there is something wrong with your lidar points, could check your lidar driver and parsing file first?

Hi and sorry for the late reply. I actually am not using any Lidar bur just the same recorded data that is given as an example. But basically i was inverting the topics so that the RS is the main one and the velodyne was the sub. I tried this because I  did not have access to real lidars at the moment, but I will be using 2 M1 RS with a 30 degree overlay and eanted to find out if this can work or not .
Thanks in advance
